
name: Build APK
on:
  # Triggers the workflow on push in develop branch
  push:
    branches: 
      - master
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # In other words: it clones the repo to the workspace to work on it there
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
    
      - name: Get Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
  
      - name: Update package list
        run: sudo apt-get update
        
      - name: Install buildozer
        run: pip install buildozer

      - name: Install dependencies
        run: |
          pip install cython
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev

      - name: Install dependencies 2
        run: |
          sudo apt-get install build-essential \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            zlib1g-dev \
            libssl-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            libncursesw5-dev \
            libffi-dev \
            uuid-dev \
            libssl-dev

      - name: Get Version
        run: echo "APP_VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build APK with debug mode enabled
        if: ${{ env.BRANCH == 'develop' }}
        run: buildozer -v android debug
        
      - name: Build APK for release
        if: ${{ env.BRANCH == 'master' }}
        run: buildozer -v android release
      
      - name: Copy debug APK
        if: ${{ env.BRANCH == 'develop' }}
        run: |
          set -e
          mv bin/KivyCamera-${{ env.APP_VERSION }}-arm64-v8a-debug.apk KivyCamera-${{ env.APP_VERSION }}-arm64-v8a-debug.apk
          
      - name: Copy release APK
        if: ${{ env.BRANCH == 'master' }}
        run: |
          set -e
          mv bin/KivyCamera-${{ env.APP_VERSION }}-arm64-v8a-release-unsigned.apk KivyCamera-${{ env.APP_VERSION }}-arm64-v8a-release-unsigned.apk
          
      - name: Release debug APK
        if: ${{ env.BRANCH == 'develop' }}
        uses: softprops/action-gh-release@v1
        with:
          name: CV2 Camera ${{ env.APP_VERSION }}
          tag_name: ${{ env.APP_VERSION }}
          body: |
            To be changed
            # This is a Debug APK.
          files: KivyCamera-${{ env.APP_VERSION }}-arm64-v8a-debug.apk
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release
        if: ${{ env.BRANCH == 'master' }}
        uses: softprops/action-gh-release@v1
        with:
          name: CV2 Camera ${{ env.APP_VERSION }}
          tag_name: ${{ env.APP_VERSION }}
          body: |
            # First release test.
            To be changed
          files: KivyCamera-${{ env.APP_VERSION }}-arm64-v8a-release-unsigned.apk
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
